server:
  port: 9000

spring:
  security:
    user:
      name: alice
      password: password
      roles:
        - user
    oauth2:
      authorizationserver:
        client:
          api-client:
            registration:
              client-id: "api-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8080/my-jaxrs-api/openapi-ui/oauth2-redirect.html"
                - "http://localhost:9080/my-jaxrs-api/openapi-ui/oauth2-redirect.html"
                - "http://localhost:9080/openapi/ui/oauth2-redirect.html"
#              post-logout-redirect-uris:
#                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "user"
            require-authorization-consent: true

logging:
  level:
    org.springframework.security: trace